[package]
name = "vivzone"
version = "0.1.0"
authors = ["Vivian Lim <vivlim@pm.me>"]
edition = "2018"

[dependencies]
askama = "0.8"
rocket = "0.4.1"
spongedown = "0.3.2"
diesel = { version = "1.4.2", features = ["sqlite"] }
sha2 = "0.8.0"
hex = "0.3.2"